#
# Copyright (C) 2018-2019 Texas Instruments Incorporated - http://www.ti.com/
#	Lokesh Vutla <lokeshvutla@ti.com>
#
# Copyright (C) 2023 TechNexion Ltd. - https://www.technexion.com/
#
# SPDX-License-Identifier:     GPL-2.0+
#

obj-y	+= rovy-4vm.o
obj-$(CONFIG_SET_DFU_ALT_INFO) += ../../ti/common/k3_dfu.o